version: '3'
services:

  djangodb:
    image: postgres:11
    hostname: django-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  djangocache:
    image: bitnami/redis:4.0
    hostname: django-redis
    volumes:
      - cache-data:/bitnami/redis/data
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

# docker volume create --name db-data
# docker volume create --name cache-data
volumes:
  db-data:
    external: true
  cache-data:
    external: true
